language: node_js
node_js:
  - '6'

install:
  - npm install -g eslint
  - npm install

script:
  - npm run lint

notifications:
  email:
    recipients:
      - kgyoo8232@gmail.com
    on_success: never
    on_failure: always